### ISSUE TITLE
Outstanding Requirements

### ISSUE THREAD

**Issue by camerican** [lisa1357mae/ShippedProject#16]
Please open issues for each of the outstanding requirements and bug fixes below and tag the issue number in your commit to receive credit for completing this assignment.

## Core Requirements
- [x]	User should be able to sign up, login and logout
- [x]	User should be able to add new boats to their profile
- [x] User should be able to assign jobs to boats
	## Required Fields
	### Boats
- [x]	Name
- [x]	Amount of containers its able to ship
- [x]	Location (stored as a string)
	### Jobs
- [ ]	Description
- [x]	Origin (stored as a string)
- [x]	Destination (stored as a string)
- [x]	Cost
- [x]	Amount of containers needed for job
- [x]	Assign boats to jobs
	## Required Validations
	### Boats
- [x]	Must have a unique name
- [x]	Locations must be pulled from a valid list of locations (use a hard-coded list)
	### Jobs
- [ ]	Must have a unique name
- [x]	Cost must be above $1000 for each job
- [ ]	Description must be at least 50 characters
- [x]	Origin and destinations must be pulled from a valid list of locations (use a hard-coded list)
- [x]	Boat should allow for an image using the paperclip gem
- [ ]	User should be able to add boats to a job using Rails UJS
- [ ]	Code is well commented and contains a README

## Bugs
- [ ] Create Boat button does not work (should send to POST /boats => boats#create)
- [ ] Should at least require login before allowing user to destroy companies!
- [ ] Should be able to add a boat to a job from the Boat or Job page -- exposing the name "BoatJob" to the end user doensn't really make sense
- [ ] The jobs table should not have a boat_id directly within it as it's a many-to-many relationship with boat...  Please explain the use-case or remove this column

**Comment by lisa1357mae** [comment]
I fixed the "create boat button" over the weekend - will look into other issues
